# Generated by Django 2.2.5 on 2019-09-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlc',
            name='gameID',
        ),
        migrations.AddField(
            model_name='item',
            name='photoLocation',
            field=models.FilePathField(allow_folders=True, default='./images/items/'),
        ),
        migrations.CreateModel(
            name='gameDLC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DLCid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.DLC')),
                ('gameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Game')),
            ],
        ),
    ]
