# Generated by Django 2.2.5 on 2019-09-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='foreignKey',
            new_name='user',
        ),
    ]
