# Generated by Django 2.2.5 on 2019-09-12 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20190912_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='game',
            name='tags',
        ),
        migrations.CreateModel(
            name='GameTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Game')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Game')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Review')),
            ],
        ),
        migrations.CreateModel(
            name='DLCTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DLCid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.DLC')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='DLCReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DLCid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.DLC')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Review')),
            ],
        ),
    ]
