# Generated by Django 2.2.5 on 2019-09-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20190915_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photoLocation',
        ),
    ]
