# Generated by Django 2.2.5 on 2019-09-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20190912_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dlcreview',
            old_name='reviews',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='dlctags',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='gamereview',
            old_name='reviews',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='gametags',
            old_name='tags',
            new_name='tag',
        ),
        migrations.AlterUniqueTogether(
            name='dlcreview',
            unique_together={('review', 'DLCid')},
        ),
        migrations.AlterUniqueTogether(
            name='dlctags',
            unique_together={('tag', 'DLCid')},
        ),
        migrations.AlterUniqueTogether(
            name='gamedlc',
            unique_together={('gameID', 'DLCid')},
        ),
        migrations.AlterUniqueTogether(
            name='gamereview',
            unique_together={('review', 'gameID')},
        ),
        migrations.AlterUniqueTogether(
            name='gametags',
            unique_together={('tag', 'gameID')},
        ),
    ]
