# Generated by Django 2.2.5 on 2019-09-15 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_item_photolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stars',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
