# Generated by Django 2.2.5 on 2019-09-15 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20190915_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemDescription',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
