# Generated by Django 2.2.5 on 2019-09-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20190912_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('listingDate', models.DateTimeField(auto_now_add=True)),
                ('buyPrice', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('BuyID', models.AutoField(primary_key=True, serialize=False)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Item')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.User')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('amount', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('transactionID', models.AutoField(primary_key=True, serialize=False)),
                ('credited_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor', to='marketplace.User')),
                ('debited_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debitor', to='marketplace.User')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('foreignKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.User')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('transactionType', models.CharField(choices=[('CR', 'Credit'), ('DR', 'Debit')], max_length=2)),
                ('WalletID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Wallet')),
                ('transactionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='transactions',
            field=models.ManyToManyField(through='marketplace.WalletTransaction', to='marketplace.Transaction'),
        ),
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('listingDate', models.DateTimeField(auto_now_add=True)),
                ('sellingPrice', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('sellorderID', models.AutoField(primary_key=True, serialize=False)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Item')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.User')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPublic', models.BinaryField(default=1)),
                ('games', models.ManyToManyField(to='marketplace.Game')),
                ('items', models.ManyToManyField(to='marketplace.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.User')),
            ],
        ),
        migrations.CreateModel(
            name='FullfilledOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillmentDate', models.DateTimeField(auto_now_add=True)),
                ('fulfillmentPrice', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('buyorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.BuyOrder')),
                ('sellOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.SellOrder')),
            ],
        ),
    ]
