# Generated by Django 2.2.5 on 2019-09-15 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auto_20190915_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemDescription',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
