# Generated by Django 2.2.5 on 2019-09-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auto_20190912_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='recovered_email',
            new_name='recovery_email',
        ),
    ]
