# Generated by Django 2.2.5 on 2019-09-15 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20190915_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
